"""Тести моделей каталогу."""
from decimal import Decimal

import pytest
from django.core.exceptions import ValidationError

from products.models import Category, Product


@pytest.mark.django_db
def test_category_slug_autogenerated() -> None:
    cat = Category.objects.create(name="Hops")
    assert cat.slug == "hops"


@pytest.mark.django_db
def test_product_slug_autogenerated() -> None:
    cat = Category.objects.create(name="Hops")
    product = Product.objects.create(name="Cascade Hops", price=Decimal("5.50"), category=cat)
    assert product.slug == "cascade-hops"


@pytest.mark.django_db
def test_product_str_is_name() -> None:
    cat = Category.objects.create(name="Hops")
    product = Product.objects.create(name="Cascade Hops", price=Decimal("5.50"), category=cat)
    assert str(product) == "Cascade Hops"


@pytest.mark.django_db
def test_product_price_cannot_be_negative() -> None:
    cat = Category.objects.create(name="Hops")
    product = Product(name="Bad", price=Decimal("-1"), category=cat)
    with pytest.raises(ValidationError):
        product.full_clean()


@pytest.mark.django_db
def test_active_manager_excludes_inactive() -> None:
    cat = Category.objects.create(name="Hops")
    Product.objects.create(name="A", price=Decimal("1"), category=cat, is_active=True)
    Product.objects.create(name="B", price=Decimal("2"), category=cat, is_active=False)
    assert Product.objects.active().count() == 1
